"""
Strings centralizadas do sistema FLIC.
Toda mensagem exibida ao usuário deve vir deste módulo.
Acesso nos templates: {{ T.chave }}
"""

T = {
    # ─── Genérico ────────────────────────────────────────────────────────────
    "salvar":                   "Salvar",
    "cancelar":                 "Cancelar",
    "confirmar":                "Confirmar",
    "excluir":                  "Excluir",
    "editar":                   "Editar",
    "voltar":                   "Voltar",
    "buscar":                   "Buscar",
    "filtrar":                  "Filtrar",
    "importar":                 "Importar",
    "exportar":                 "Exportar",
    "adicionar":                "Adicionar",
    "remover":                  "Remover",
    "ativo":                    "Ativo",
    "inativo":                  "Inativo",
    "sim":                      "Sim",
    "nao":                      "Não",
    "todos":                    "Todos",
    "nenhum_registro":          "Nenhum registro encontrado.",
    "carregando":               "Carregando...",
    "periodo_de":               "De",
    "periodo_ate":              "Até",
    "gerar":                    "Gerar",

    # ─── Erros genéricos ─────────────────────────────────────────────────────
    "erro_acesso_negado":       "Acesso negado.",
    "erro_registro_nao_encontrado": "Registro não encontrado.",
    "erro_cliente_invalido":    "Cliente inválido ou sem permissão de acesso.",
    "erro_inesperado":          "Erro inesperado. Tente novamente.",

    # ─── Autenticação ─────────────────────────────────────────────────────────
    "login_titulo":             "Entrar na sua conta",
    "login_email":              "E-mail",
    "login_senha":              "Senha",
    "login_btn":                "Entrar",
    "login_erro_credenciais":   "E-mail ou senha incorretos.",
    "login_erro_inativo":       "Usuário inativo. Entre em contato com o administrador.",
    "logout_sucesso":           "Sessão encerrada com sucesso.",

    # ─── Lançamentos ─────────────────────────────────────────────────────────
    "lanc_titulo":              "Lançamentos de Atendimento",
    "lanc_novo":                "Novo lançamento",
    "lanc_salvar":              "Salvar lançamento",
    "lanc_salvar_n":            "Salvar {n} lançamentos",
    "lanc_recentes":            "Lançamentos",
    "lanc_nenhum":              "Nenhum lançamento encontrado no período.",
    "lanc_adicionarLinha":      "+ Adicionar serviço",
    "lanc_expandir":            "Expandir / Recolher",
    "lanc_erro_cliente":        "Selecione o cliente.",
    "lanc_erro_data":           "Informe a data do atendimento.",
    "lanc_erro_valor":          "Informe o valor de ao menos um serviço.",
    "lanc_conciliado_edit":     "Atendimento já conciliado, não pode ser editado.",
    "lanc_conciliado_excluir":  "Atendimento já conciliado, não pode ser excluído.",
    "lanc_editar_titulo":       "Editar Lançamento",
    "lanc_salvar_alteracoes":   "Salvar alterações",
    "lanc_excluir_confirm":     "Excluir este lançamento?",

    # ─── Conciliação Cartão ───────────────────────────────────────────────────
    "cc_titulo":                "Conciliação Cartão",
    "cc_importar_extrato":      "Importar extrato da maquininha",
    "cc_importar_lancamentos":  "Importar lançamentos",
    "cc_conciliar_prontos":     "Conciliar todos os prontos",
    "cc_fechar_lote":           "Fechar lote",
    "cc_desfazer_lote":         "↩ Desfazer lote",
    "cc_reabrir_lote":          "↩ Reabrir",
    "cc_desvincular_venda":     "↩ Desvincular",
    "cc_trocar":                "Trocar",
    "cc_editar":                "✏ Editar",
    "cc_conciliar":             "Conciliar",
    "cc_sugestao_pronta":       "Encontramos",
    "cc_quase_la":              "Quase lá",
    "cc_sem_sugestao":          "Sem sugestão",
    "cc_prontos_fechar":        "Prontos para fechar lote",
    "cc_lotes_aguardando":      "lote(s) aguardando conciliação bancária",
    "cc_lotes_conciliados":     "lote(s) conciliado(s)",
    "cc_desfazer_confirm":      "Desfazer este lote? As vendas voltam para 'Prontos para fechar' e o vínculo bancário será desfeito se existir.",
    "cc_reabrir_confirm":       "Reabrir este lote? O vínculo com o extrato bancário também será desfeito.",
    "cc_importado_sucesso":     "{total} venda(s) importada(s) de '{arquivo}'.",
    "cc_lancamentos_importados":"  {total} lançamento(s) importado(s) de '{arquivo}'.",
    "cc_nenhuma_venda":         "Nenhuma venda pendente no momento.",
    "cc_ir_banco":              "Ir para Conciliação Banco →",

    # ─── Conciliação Banco ────────────────────────────────────────────────────
    "cb_titulo":                "Conciliação Banco",
    "cb_importar_extrato":      "Importar extrato bancário",
    "cb_importar_lancamentos":  "Importar lançamentos",
    "cb_conciliar_prontos":     "Conciliar todos os prontos",
    "cb_auto_match_lotes":      "Conciliar todos os lotes",
    "cb_auto_match_saidas":     "Conciliar todas as saídas",
    "cb_conciliar":             "Conciliar",
    "cb_confirmar":             "Confirmar",
    "cb_desvincular":           "↩ Desvincular",
    "cb_trocar":                "Trocar",
    "cb_revisar":               "Revisar",
    "cb_criar_e_conciliar":     "Criar e conciliar",
    "cb_buscar_lancamento":     "🔍 Buscar lançamento",
    "cb_novo_lancamento":       "+ Novo lançamento",
    "cb_pix_conciliados":       "recebimento(s) conciliado(s)",
    "cb_desvincular_pix_confirm": "Desvincular este recebimento do atendimento?",
    "cb_saidas_conciliadas":    "saída(s) conciliada(s)",
    "cb_desvincular_saida_confirm": "Desvincular esta saída da conta a pagar? A conta voltará para 'Agendado'.",
    "cb_expandir_desvincular":  "▸ expandir para desvincular",
    "cb_aguardando_debito":     "Aguardando débito no extrato",
    "cb_importar_extrato_instrucao": "Importe o extrato bancário",
    "cb_nenhuma_saida":         "Nenhuma saída ou conta agendada",
    "cb_nenhuma_saida_sub":     "Agende contas a pagar e importe o extrato bancário para conciliar",
    "cb_lote_fechado_flash":    "Lote {bandeira} {data} fechado — R$ {valor} aguardando crédito bancário.",
    "cb_extrato_importado":     "{n} linha(s) importada(s) de '{arquivo}'.",
    "cb_extrato_auto":          " {n} lote(s) auto-conciliado(s).",
    "cb_lancamentos_importados":"  {n} lançamento(s) importado(s) de '{arquivo}'.",

    # ─── Contas a Pagar ───────────────────────────────────────────────────────
    "cp_titulo":                "Contas a Pagar",
    "cp_nova":                  "Nova conta",
    "cp_salvar":                "Salvar conta",
    "cp_agendar":               "Agendar",
    "cp_cancelar":              "Cancelar",
    "cp_importar":              "Importar planilha",
    "cp_nenhuma":               "Nenhuma conta a pagar encontrada.",
    "cp_status_pendente":       "Pendente",
    "cp_status_aguardando":     "Aguardando aprovação",
    "cp_status_agendado":       "Agendado",
    "cp_status_pago":           "Pago",
    "cp_status_cancelado":      "Cancelado",
    "cp_importado_sucesso":     "{n} conta(s) importada(s) de '{arquivo}'.",
    "cp_cancelar_confirm":      "Cancelar esta conta?",
    "cp_erro_cancelar_pago":    "Não é possível cancelar uma conta já paga.",

    # ─── Fechamento ───────────────────────────────────────────────────────────
    "fech_titulo":              "Fechamento",
    "fech_mensal_titulo":       "Fechamento Mensal",
    "fech_gerar":               "Gerar fechamento",
    "fech_total_receitas":      "Total Receitas",
    "fech_total_despesas":      "Total Despesas",
    "fech_resultado":           "Resultado do Período",
    "fech_receitas_banco":      "Recebimentos confirmados no banco",
    "fech_lotes_cartao":        "Lotes de cartão conciliados no banco",
    "fech_despesas_pagas":      "Despesas pagas no período",
    "fech_sem_receita":         "Nenhuma receita confirmada no banco neste período.",
    "fech_sem_receita_sub":     "As receitas só aparecem após a Conciliação Banco ser finalizada.",
    "fech_sem_despesa":         "Nenhuma despesa paga neste período.",
    "fech_resultado_final":     "Resultado final do período",
    "fech_receitas_menos_desp": "Receitas − Despesas",

    # ─── Admin ────────────────────────────────────────────────────────────────
    "adm_titulo_clientes":      "Clientes",
    "adm_titulo_taxas":         "Taxas de Cartão por Cliente",
    "adm_taxa_salvar":          "Salvar taxa",
    "adm_taxa_remover":         "Remover",
    "adm_taxa_existente":       "Se já existir uma taxa para essa bandeira + faixa, ela será atualizada.",
    "adm_antecipa_ativar":      "Ativar antecipação",
    "adm_antecipa_desativar":   "Desativar antecipação",
    "adm_ant_adicionar":        "Adicionar taxa de antecipação",
    "adm_ant_usar_esta":        "Usar esta",
    "adm_ant_desativar":        "Desativar",
    "adm_ant_reativar":         "Reativar",
    "adm_ant_excluir":          "Excluir",
    "adm_ant_ativa":            "✓ Ativa no período",
    "adm_ant_desativada":       "Desativada",
    "adm_ant_inativa":          "—",
    "adm_ant_excluir_confirm":  "Excluir permanentemente esta taxa?",
    "adm_ant_rodape":           "A taxa marcada como \"Ativa no período\" é usada automaticamente no cálculo dos lançamentos de cartão para este cliente.",

    # ─── Rotinas ─────────────────────────────────────────────────────────────
    "rot_titulo":               "Rotinas",
    "rot_concluir":             "Concluir",
    "rot_nenhuma":              "Nenhuma rotina cadastrada.",

    # ─── Dashboard ────────────────────────────────────────────────────────────
    "dash_titulo":              "Dashboard",
    "dash_contas_pendentes":    "Contas pendentes",
    "dash_sem_dados":           "Nenhum dado disponível.",

    # ─── Logs ─────────────────────────────────────────────────────────────────
    "log_titulo":               "Logs de Auditoria",
    "log_nenhum":               "Nenhum log encontrado.",

    # ─── Status conciliação ───────────────────────────────────────────────────
    "status_pendente":          "Pendente",
    "status_conciliado":        "Conciliado",
    "status_divergencia":       "Divergência",
    "status_importada":         "Importada",
    "status_conciliada":        "Conciliada",
    "status_revisada":          "Revisada",
    "status_fechado":           "Fechado",
    "status_cancelado":         "Cancelado",

    # ─── Confirmações genéricas ───────────────────────────────────────────────
    "confirm_excluir":          "Tem certeza que deseja excluir?",
    "confirm_cancelar":         "Tem certeza que deseja cancelar?",
    "confirm_desvincular":      "Tem certeza que deseja desvincular?",
}
